name: Deploy Blog 

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./blog
        run: npm install
      
      - name: Install stable Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      
      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown
      
      - name: Lint
        run: cargo clippy && cargo fmt --check
      
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.18.4/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      
      - name: Build with Trunk
        working-directory: ./blog
        run: ../trunk build --release
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
      
      - name: Create CNAME file
        run: echo "blog.handamin.com" > blog/dist/CNAME
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./blog/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
